# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prix2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_segunda(object):
    def setupUi(self, segunda):
        segunda.setObjectName("segunda")
        segunda.resize(640, 516)
        self.centralwidget = QtWidgets.QWidget(segunda)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.combo = QtWidgets.QComboBox(self.centralwidget)
        self.combo.setGeometry(QtCore.QRect(150, 80, 111, 31))
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.combo.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(420, 81, 81, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.s1 = QtWidgets.QComboBox(self.centralwidget)
        self.s1.setGeometry(QtCore.QRect(80, 170, 131, 22))
        self.s1.setObjectName("s1")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.s1.addItem("")
        self.c1 = QtWidgets.QSpinBox(self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(80, 200, 51, 22))
        self.c1.setSuffix("")
        self.c1.setMaximum(100000)
        self.c1.setObjectName("c1")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(140, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(250, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 350, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(500, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(370, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.d1 = QtWidgets.QSpinBox(self.centralwidget)
        self.d1.setGeometry(QtCore.QRect(161, 350, 51, 22))
        self.d1.setMaximum(100000)
        self.d1.setObjectName("d1")
        self.d5 = QtWidgets.QSpinBox(self.centralwidget)
        self.d5.setGeometry(QtCore.QRect(161, 380, 51, 22))
        self.d5.setMaximum(100000)
        self.d5.setObjectName("d5")
        self.d2 = QtWidgets.QSpinBox(self.centralwidget)
        self.d2.setGeometry(QtCore.QRect(271, 350, 51, 22))
        self.d2.setMaximum(100000)
        self.d2.setObjectName("d2")
        self.d6 = QtWidgets.QSpinBox(self.centralwidget)
        self.d6.setGeometry(QtCore.QRect(271, 380, 51, 22))
        self.d6.setMaximum(100000)
        self.d6.setObjectName("d6")
        self.d3 = QtWidgets.QSpinBox(self.centralwidget)
        self.d3.setGeometry(QtCore.QRect(391, 350, 51, 22))
        self.d3.setMaximum(100000)
        self.d3.setObjectName("d3")
        self.d7 = QtWidgets.QSpinBox(self.centralwidget)
        self.d7.setGeometry(QtCore.QRect(391, 380, 51, 22))
        self.d7.setMaximum(100000)
        self.d7.setObjectName("d7")
        self.d4 = QtWidgets.QSpinBox(self.centralwidget)
        self.d4.setGeometry(QtCore.QRect(521, 350, 51, 22))
        self.d4.setMaximum(100000)
        self.d4.setObjectName("d4")
        self.d8 = QtWidgets.QSpinBox(self.centralwidget)
        self.d8.setGeometry(QtCore.QRect(521, 380, 51, 22))
        self.d8.setMaximum(100000)
        self.d8.setObjectName("d8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 320, 641, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton11.setGeometry(QtCore.QRect(420, 440, 75, 23))
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 440, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 440, 41, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 641, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 130, 641, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.c2 = QtWidgets.QSpinBox(self.centralwidget)
        self.c2.setGeometry(QtCore.QRect(220, 200, 51, 22))
        self.c2.setMaximum(100000)
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QSpinBox(self.centralwidget)
        self.c3.setGeometry(QtCore.QRect(360, 200, 51, 22))
        self.c3.setMaximum(100000)
        self.c3.setObjectName("c3")
        self.c4 = QtWidgets.QSpinBox(self.centralwidget)
        self.c4.setGeometry(QtCore.QRect(500, 200, 51, 22))
        self.c4.setMaximum(100000)
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QSpinBox(self.centralwidget)
        self.c5.setGeometry(QtCore.QRect(80, 270, 51, 22))
        self.c5.setMaximum(100000)
        self.c5.setObjectName("c5")
        self.c8 = QtWidgets.QSpinBox(self.centralwidget)
        self.c8.setGeometry(QtCore.QRect(500, 270, 51, 22))
        self.c8.setMaximum(100000)
        self.c8.setObjectName("c8")
        self.c7 = QtWidgets.QSpinBox(self.centralwidget)
        self.c7.setGeometry(QtCore.QRect(360, 270, 51, 22))
        self.c7.setMaximum(100000)
        self.c7.setObjectName("c7")
        self.c6 = QtWidgets.QSpinBox(self.centralwidget)
        self.c6.setGeometry(QtCore.QRect(220, 270, 51, 22))
        self.c6.setMaximum(100000)
        self.c6.setObjectName("c6")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(220, 350, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(220, 380, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(330, 350, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(330, 380, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(450, 350, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(450, 380, 16, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(580, 350, 16, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(580, 380, 16, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(140, 200, 16, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(280, 200, 16, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(420, 200, 16, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(560, 200, 16, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(140, 270, 16, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(280, 270, 16, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(420, 270, 16, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(560, 270, 16, 16))
        self.label_30.setObjectName("label_30")
        self.s2 = QtWidgets.QComboBox(self.centralwidget)
        self.s2.setGeometry(QtCore.QRect(220, 170, 131, 22))
        self.s2.setObjectName("s2")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s2.addItem("")
        self.s3 = QtWidgets.QComboBox(self.centralwidget)
        self.s3.setGeometry(QtCore.QRect(360, 170, 131, 22))
        self.s3.setObjectName("s3")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s3.addItem("")
        self.s4 = QtWidgets.QComboBox(self.centralwidget)
        self.s4.setGeometry(QtCore.QRect(500, 170, 131, 22))
        self.s4.setObjectName("s4")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s4.addItem("")
        self.s5 = QtWidgets.QComboBox(self.centralwidget)
        self.s5.setGeometry(QtCore.QRect(80, 240, 131, 22))
        self.s5.setObjectName("s5")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s5.addItem("")
        self.s6 = QtWidgets.QComboBox(self.centralwidget)
        self.s6.setGeometry(QtCore.QRect(220, 240, 131, 22))
        self.s6.setObjectName("s6")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s6.addItem("")
        self.s7 = QtWidgets.QComboBox(self.centralwidget)
        self.s7.setGeometry(QtCore.QRect(360, 240, 131, 22))
        self.s7.setObjectName("s7")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.s7.addItem("")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap(":/logo1/logo.gif"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(594, 0, 41, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(540, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcd.setFont(font)
        self.lcd.setAutoFillBackground(False)
        self.lcd.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.lcd.setDigitCount(1)
        self.lcd.setProperty("intValue", 0)
        self.lcd.setObjectName("lcd")
        self.s8 = QtWidgets.QTextEdit(self.centralwidget)
        self.s8.setGeometry(QtCore.QRect(500, 240, 104, 21))
        self.s8.setObjectName("s8")
        self.B3 = QtWidgets.QPushButton(self.centralwidget)
        self.B3.setGeometry(QtCore.QRect(314, 440, 101, 23))
        self.B3.setObjectName("B3")
        segunda.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(segunda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        segunda.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(segunda)
        self.statusbar.setObjectName("statusbar")
        segunda.setStatusBar(self.statusbar)

        self.retranslateUi(segunda)
        QtCore.QMetaObject.connectSlotsByName(segunda)

    def retranslateUi(self, segunda):
        _translate = QtCore.QCoreApplication.translate
        segunda.setWindowTitle(_translate("segunda", "MainWindow"))
        self.label.setText(_translate("segunda", "Ingrese Condiciones de la Instalación"))
        self.label_2.setText(_translate("segunda", "Tipo"))
        self.label_3.setText(_translate("segunda", "Condición"))
        self.combo.setItemText(0, _translate("segunda", "Almacenamiento"))
        self.combo.setItemText(1, _translate("segunda", "Proceso"))
        self.comboBox_2.setItemText(0, _translate("segunda", "Abierto"))
        self.comboBox_2.setItemText(1, _translate("segunda", "Cerrado"))
        self.comboBox_2.setItemText(2, _translate("segunda", "Condicion A"))
        self.comboBox_2.setItemText(3, _translate("segunda", "Condicion B"))
        self.label_4.setText(_translate("segunda", "Sustancia"))
        self.label_5.setText(_translate("segunda", "Cantidad"))
        self.s1.setItemText(0, _translate("segunda", "Select"))
        self.s1.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s1.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s1.setItemText(3, _translate("segunda", "Xileno"))
        self.s1.setItemText(4, _translate("segunda", "Tolueno"))
        self.s1.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s1.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s1.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s1.setItemText(8, _translate("segunda", "Etileno"))
        self.s1.setItemText(9, _translate("segunda", "Etano"))
        self.s1.setItemText(10, _translate("segunda", "Butano"))
        self.s1.setItemText(11, _translate("segunda", "Propileno"))
        self.s1.setItemText(12, _translate("segunda", "Propano"))
        self.s1.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s1.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s1.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s1.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s1.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s1.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s1.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s1.setItemText(20, _translate("segunda", "ANFO"))
        self.s1.setItemText(21, _translate("segunda", "RDX"))
        self.s1.setItemText(22, _translate("segunda", "Acroleina"))
        self.s1.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s1.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s1.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s1.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s1.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s1.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s1.setItemText(29, _translate("segunda", "Cloro"))
        self.label_6.setText(_translate("segunda", "Ubicaciones "))
        self.label_7.setText(_translate("segunda", "1"))
        self.label_8.setText(_translate("segunda", "2"))
        self.label_9.setText(_translate("segunda", "3"))
        self.label_10.setText(_translate("segunda", "5"))
        self.label_11.setText(_translate("segunda", "4"))
        self.label_12.setText(_translate("segunda", "7"))
        self.label_13.setText(_translate("segunda", "8"))
        self.label_14.setText(_translate("segunda", "6"))
        self.pushButton11.setText(_translate("segunda", "Guardar "))
        self.pushButton_3.setText(_translate("segunda", "Generar"))
        self.pushButton_4.setText(_translate("segunda", "Salir"))
        self.label_15.setText(_translate("segunda", "m"))
        self.label_16.setText(_translate("segunda", "m"))
        self.label_17.setText(_translate("segunda", "m"))
        self.label_18.setText(_translate("segunda", "m"))
        self.label_19.setText(_translate("segunda", "m"))
        self.label_20.setText(_translate("segunda", "m"))
        self.label_21.setText(_translate("segunda", "m"))
        self.label_22.setText(_translate("segunda", "m"))
        self.label_23.setText(_translate("segunda", "Kg"))
        self.label_24.setText(_translate("segunda", "Kg"))
        self.label_25.setText(_translate("segunda", "Kg"))
        self.label_26.setText(_translate("segunda", "Kg"))
        self.label_27.setText(_translate("segunda", "Kg"))
        self.label_28.setText(_translate("segunda", "Kg"))
        self.label_29.setText(_translate("segunda", "Kg"))
        self.label_30.setText(_translate("segunda", "Kg"))
        self.s2.setItemText(0, _translate("segunda", "Select"))
        self.s2.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s2.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s2.setItemText(3, _translate("segunda", "Xileno"))
        self.s2.setItemText(4, _translate("segunda", "Tolueno"))
        self.s2.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s2.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s2.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s2.setItemText(8, _translate("segunda", "Etileno"))
        self.s2.setItemText(9, _translate("segunda", "Etano"))
        self.s2.setItemText(10, _translate("segunda", "Butano"))
        self.s2.setItemText(11, _translate("segunda", "Propileno"))
        self.s2.setItemText(12, _translate("segunda", "Propano"))
        self.s2.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s2.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s2.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s2.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s2.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s2.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s2.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s2.setItemText(20, _translate("segunda", "ANFO"))
        self.s2.setItemText(21, _translate("segunda", "RDX"))
        self.s2.setItemText(22, _translate("segunda", "Acroleina"))
        self.s2.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s2.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s2.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s2.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s2.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s2.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s2.setItemText(29, _translate("segunda", "Cloro"))
        self.s3.setItemText(0, _translate("segunda", "Select"))
        self.s3.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s3.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s3.setItemText(3, _translate("segunda", "Xileno"))
        self.s3.setItemText(4, _translate("segunda", "Tolueno"))
        self.s3.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s3.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s3.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s3.setItemText(8, _translate("segunda", "Etileno"))
        self.s3.setItemText(9, _translate("segunda", "Etano"))
        self.s3.setItemText(10, _translate("segunda", "Butano"))
        self.s3.setItemText(11, _translate("segunda", "Propileno"))
        self.s3.setItemText(12, _translate("segunda", "Propano"))
        self.s3.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s3.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s3.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s3.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s3.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s3.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s3.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s3.setItemText(20, _translate("segunda", "ANFO"))
        self.s3.setItemText(21, _translate("segunda", "RDX"))
        self.s3.setItemText(22, _translate("segunda", "Acroleina"))
        self.s3.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s3.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s3.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s3.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s3.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s3.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s3.setItemText(29, _translate("segunda", "Cloro"))
        self.s4.setItemText(0, _translate("segunda", "Select"))
        self.s4.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s4.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s4.setItemText(3, _translate("segunda", "Xileno"))
        self.s4.setItemText(4, _translate("segunda", "Tolueno"))
        self.s4.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s4.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s4.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s4.setItemText(8, _translate("segunda", "Etileno"))
        self.s4.setItemText(9, _translate("segunda", "Etano"))
        self.s4.setItemText(10, _translate("segunda", "Butano"))
        self.s4.setItemText(11, _translate("segunda", "Propileno"))
        self.s4.setItemText(12, _translate("segunda", "Propano"))
        self.s4.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s4.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s4.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s4.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s4.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s4.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s4.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s4.setItemText(20, _translate("segunda", "ANFO"))
        self.s4.setItemText(21, _translate("segunda", "RDX"))
        self.s4.setItemText(22, _translate("segunda", "Acroleina"))
        self.s4.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s4.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s4.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s4.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s4.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s4.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s4.setItemText(29, _translate("segunda", "Cloro"))
        self.s5.setItemText(0, _translate("segunda", "Select"))
        self.s5.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s5.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s5.setItemText(3, _translate("segunda", "Xileno"))
        self.s5.setItemText(4, _translate("segunda", "Tolueno"))
        self.s5.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s5.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s5.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s5.setItemText(8, _translate("segunda", "Etileno"))
        self.s5.setItemText(9, _translate("segunda", "Etano"))
        self.s5.setItemText(10, _translate("segunda", "Butano"))
        self.s5.setItemText(11, _translate("segunda", "Propileno"))
        self.s5.setItemText(12, _translate("segunda", "Propano"))
        self.s5.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s5.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s5.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s5.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s5.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s5.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s5.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s5.setItemText(20, _translate("segunda", "ANFO"))
        self.s5.setItemText(21, _translate("segunda", "RDX"))
        self.s5.setItemText(22, _translate("segunda", "Acroleina"))
        self.s5.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s5.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s5.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s5.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s5.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s5.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s5.setItemText(29, _translate("segunda", "Cloro"))
        self.s6.setItemText(0, _translate("segunda", "Select"))
        self.s6.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s6.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s6.setItemText(3, _translate("segunda", "Xileno"))
        self.s6.setItemText(4, _translate("segunda", "Tolueno"))
        self.s6.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s6.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s6.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s6.setItemText(8, _translate("segunda", "Etileno"))
        self.s6.setItemText(9, _translate("segunda", "Etano"))
        self.s6.setItemText(10, _translate("segunda", "Butano"))
        self.s6.setItemText(11, _translate("segunda", "Propileno"))
        self.s6.setItemText(12, _translate("segunda", "Propano"))
        self.s6.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s6.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s6.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s6.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s6.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s6.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s6.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s6.setItemText(20, _translate("segunda", "ANFO"))
        self.s6.setItemText(21, _translate("segunda", "RDX"))
        self.s6.setItemText(22, _translate("segunda", "Acroleina"))
        self.s6.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s6.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s6.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s6.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s6.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s6.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s6.setItemText(29, _translate("segunda", "Cloro"))
        self.s7.setItemText(0, _translate("segunda", "Select"))
        self.s7.setItemText(1, _translate("segunda", "Acido Propionico"))
        self.s7.setItemText(2, _translate("segunda", "Acetato de Etilo"))
        self.s7.setItemText(3, _translate("segunda", "Xileno"))
        self.s7.setItemText(4, _translate("segunda", "Tolueno"))
        self.s7.setItemText(5, _translate("segunda", "Amoniaco"))
        self.s7.setItemText(6, _translate("segunda", "Monoxido de Carbono"))
        self.s7.setItemText(7, _translate("segunda", "Cloruro de Hidrogeno"))
        self.s7.setItemText(8, _translate("segunda", "Etileno"))
        self.s7.setItemText(9, _translate("segunda", "Etano"))
        self.s7.setItemText(10, _translate("segunda", "Butano"))
        self.s7.setItemText(11, _translate("segunda", "Propileno"))
        self.s7.setItemText(12, _translate("segunda", "Propano"))
        self.s7.setItemText(13, _translate("segunda", "Nitrato de Potasio"))
        self.s7.setItemText(14, _translate("segunda", "Clorato de Potasio"))
        self.s7.setItemText(15, _translate("segunda", "Nitroglicerina"))
        self.s7.setItemText(16, _translate("segunda", "Trinitrotolueno"))
        self.s7.setItemText(17, _translate("segunda", "Acetiluro de Plata"))
        self.s7.setItemText(18, _translate("segunda", "Nitrocelulosa"))
        self.s7.setItemText(19, _translate("segunda", "Ciclonita"))
        self.s7.setItemText(20, _translate("segunda", "ANFO"))
        self.s7.setItemText(21, _translate("segunda", "RDX"))
        self.s7.setItemText(22, _translate("segunda", "Acroleina"))
        self.s7.setItemText(23, _translate("segunda", "Acrilonitrilo"))
        self.s7.setItemText(24, _translate("segunda", "Cianuro de Hidrogeno"))
        self.s7.setItemText(25, _translate("segunda", "Fluoruro de Hidrogeno"))
        self.s7.setItemText(26, _translate("segunda", "Sulfuro de Hidrogeno"))
        self.s7.setItemText(27, _translate("segunda", "Dioxido de Nitrogeno"))
        self.s7.setItemText(28, _translate("segunda", "Dioxido de Azufre"))
        self.s7.setItemText(29, _translate("segunda", "Cloro"))
        self.label_31.setToolTip(_translate("segunda", "<html><head/><body><p><img src=\":/oscar1/logo.gif\"/></p></body></html>"))
        self.pushButton_11.setText(_translate("segunda", "ayuda"))
        self.B3.setText(_translate("segunda", "Añadir sustancia"))

import logo1
